name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'
    - name: Create conda environment
      run: |
        conda create --name my_env python=3.10
    - name: Activate conda environment
      run: |
        conda activate my_env
    - name: Install dependencies
      run: |
        conda install -c conda-forge scikit-learn streamlit numpy pandas

  # Add additional steps to build and deploy your Streamlit app
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest

