name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Print current directory
      run: pwd
    - name: Create conda environment
      run: |
        conda create --name my_env python=3.10
    - name: Initialize conda
      run: |
        conda init bash
        exec bash
        conda activate my_env
    - name: Install dependencies
      run: |
        conda install -c conda-forge scikit-learn streamlit numpy pandas

  # Add additional steps to build and deploy your Streamlit app
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run Flake8
      run: |
        flake8 --exclude=venv
    - name: Install pytest
      run: |
        conda install -c anaconda pytest
    - name: Run tests
      run: |
        pytest

